import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab beatae
        obcaecati commodi error non itaque velit eum consequatur tempore, eaque
        suscipit accusantium culpa fugiat, est aliquam exercitationem, possimus
        totam architecto? Exercitationem corporis sapiente laudantium id non
        dolorum doloribus officiis provident.
      </main>
    </>
  );
}
